### ISSUE TITLE
Multimedia Gallery (3)

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-fe#19]
As Nova, I need a to see the practices in real life through photos of people facilitating or videos of how to do it so that I can make a decision about how valuable the information will be for my needs.

**ACCEPTANCE CRITERIA** 

**Given** I scroll to the Media section on any Practice page
**When** I see a gallery with photos 
**Then** I can select thumbnails to view larger.

**NOTES**
- Full practice page: https://zpl.io/amAnrdr
- Needs designs for the interaction of adding a photo or video (may be a form for MVP)
- Add media story https://github.com/openpracticelibrary/opl-fe/issues/27

**Comment by Venus-Izadi** [comment]
- Gallery shows images, with the same width, but different heights. The gallery box resizes for small images,

- default image (when it can't open an image or anything goes wrong), is the grey image. At the moment that gray image is there because the video link can't be rendered like images and so it shows an error.

**Comment by DarcieF** [comment]
The gallery should not resize based on height of photo, we need to look at a unified size for all images so that the look & feel is consistent. This may mean having a minimum size for the image but the goal would be that gallery is always the same size. It is interruptive to the user experience, look & feel, branding and upcoming visual design to have it resize. This can be part of a Refinement story need for Design pairing: https://github.com/openpracticelibrary/opl-fe/issues/52
